// Admin UI copy. The panel itself is bilingual — staff read Arabic — and flips
// dir like the public site. Same discipline as lib/dictionary.ts: `en` is
// type-checked against the `ar` shape, so a missing translation is a build error.

const ar = {
  brand: "ريد أور نيود",
  panel: "لوحة التحكم",

  nav: {
    dashboard: "الرئيسية",
    bookings: "الحجوزات",
    noShows: "لم يحضروا",
    frontDesk: "الاستقبال",
    floor: "طاقم اليوم",
    availability: "أوقات العمل",
    catalog: "الخدمات",
    media: "مكتبة الصور",
    designs: "التصاميم",
    customers: "العملاء",
    giftCards: "بطاقات الهدايا",
    staff: "الموظفون",
    technicians: "الفنيات",
    performance: "الأداء",
    reviews: "التقييمات",
    branches: "الفروع",
    content: "المحتوى",
    promoCodes: "أكواد الخصم",
    marketing: "التسويق",
    settings: "الإعدادات",
    auditLog: "سجل النشاط",
  },

  groups: {
    operations: "العمليات",
    catalogue: "الكتالوج",
    people: "الأشخاص",
    site: "الموقع",
    system: "النظام",
  },

  login: {
    title: "تسجيل الدخول",
    subtitle: "لوحة تحكم ريد أور نيود",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    submit: "دخول",
    submitting: "جارٍ الدخول…",
    invalid: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    error: "تعذر تسجيل الدخول، حاول مرة أخرى",
    staffOnly: "هذه الصفحة للموظفين فقط",
  },

  topbar: {
    allBranches: "كل الفروع",
    branch: "الفرع",
    signOut: "تسجيل الخروج",
    search: "بحث",
    account: "الحساب",
  },

  dashboard: {
    title: "الرئيسية",
    welcome: "أهلاً",
    todayBookings: "حجوزات اليوم",
    upcoming: "المواعيد القادمة",
    revenueToday: "إيرادات اليوم",
    utilisation: "إشغال الكراسي",
    services: "الخدمات المفعّلة",
    customers: "العملاء",
    denied: "لا تملك صلاحية الوصول إلى هذا القسم",
    vsLastWeek: "عن الأسبوع الماضي",
    chairHours: (sold: number, total: number) => `${sold} من ${total} ساعة كرسي مباعة`,
    hoursUnsold: (hours: number) => `${hours} ساعة غير مباعة`,
    noShowsWeek: "لم تحضر هذا الأسبوع",
    branchesToday: "الفروع اليوم",
    openBranch: "اضغطي على الفرع لفتح يومه",
    topServices: "أكثر الخدمات اليوم",
    byRevenue: "حسب الإيراد",
    techniciansToday: "الفنيات اليوم",
    doneAvg: "منجزة · المتوسط",
    booked: (n: number) => `${n} حجز`,
    techniciansIn: (n: number) => `${n} فنية في الفرع`,
    needsYou: "يحتاج انتباهك",
    allQuiet: "لا شيء يحتاج انتباهك الآن.",
    unassigned: "حجوزات بدون فنية",
    lowReview: (rating: number) => `تقييم ${rating} من ٥`,
    onLeave: "في إجازة",
    assign: "تعيين",
  },

  audit: {
    title: "سجل النشاط",
    subtitle: "كل تعديل على الأسعار والحجوزات يُسجَّل هنا",
    actor: "المستخدم",
    action: "الإجراء",
    entity: "العنصر",
    when: "التاريخ",
    changes: "التغييرات",
    empty: "لا يوجد نشاط مسجل بعد",
  },

  bookings: {
    title: "الحجوزات",
    onThisDay: "حجز في هذا اليوم",
    walkIn: "حجز مباشر",
    create: "إنشاء الحجز",
    dayView: "اليوم",
    listView: "قائمة",
    prevDay: "اليوم السابق",
    nextDay: "اليوم التالي",
    date: "التاريخ",
    jumpToday: "اليوم",
    station: "كرسي",
    time: "الوقت",
    customer: "العميل",
    phone: "رقم الجوال",
    service: "الخدمة",
    addons: "الإضافات",
    removal: "الإزالة",
    status: "الحالة",
    total: "الإجمالي",
    code: "رقم الحجز",
    refillOf: "إعادة تعبئة لحجز",
    refillDays: "الأيام",
    source: "المصدر",
    notes: "ملاحظات",
    empty: "لا توجد حجوزات في هذا اليوم",
    noStations: "لا توجد كراسي معرّفة لهذا الفرع",
    noStationsBody: "تُضاف الكراسي من صفحة أوقات العمل حتى يمكن استقبال الحجوزات.",
    noSlots: "لا توجد مواعيد متاحة",
    pickTime: "اختيار الوقت",
    slotTaken: "تم حجز هذا الوقت للتو، يُرجى اختيار وقت آخر",
    changeStatus: "تغيير الحالة",
    reschedule: "تغيير الموعد",
    rescheduleOn: "اليوم",
    rescheduleCurrent: "الموعد الحالي",
    rescheduled: "تم نقل الموعد.",
    del: "حذف الحجز",
    delConfirm: "حذف هذا الحجز نهائياً؟ لا يمكن التراجع. لإنهاء موعد حقيقي استخدمي «إلغاء».",
    delConfirmGroup: (n: number) => `سيُحذف ${n} حجوزات — الحجز الجماعي كاملاً. لا يمكن التراجع.`,
    delHasPayment: "لا يمكن حذف حجز مدفوع. استخدمي الإلغاء بدلاً منه.",
    delHasReview: "لا يمكن حذف حجز عليه تقييم من العميلة.",
    delHasPoints: "لا يمكن حذف حجز احتُسبت عليه نقاط ولاء.",
    group: "حجز جماعي",
    groupOf: (letter: string, n: number) => `مجموعة ${letter} · ${n}`,
    groupLetter: (letter: string) => `مجموعة ${letter}`,
    groupWith: "محجوز مع",
    groupNote: "حجزتا معاً — فاتورة واحدة، وتصلان معاً.",
    tabBooked: "الحجوزات",
    tabDropped: "ملغاة ولم تحضر",
    droppedEmpty: "لا توجد حجوزات ملغاة أو لم تحضر في هذا اليوم.",
    pageOf: (from: number, to: number, total: number) => `${from}–${to} من ${total}`,
    prevPage: "السابق",
    nextPage: "التالي",
    cancelReason: "سبب الإلغاء (اختياري)",
    optional: "اختياري",
    // The action that marks arrival. The *badge* still reads "جارٍ التنفيذ" —
    // only the button is renamed, because pressing it is now what the 20-minute
    // no-show rule measures, and "تسجيل الحضور" says that and "بدء" does not.
    checkIn: "تسجيل الحضور",
    noShowTitle: "حجوزات لم يحضر أصحابها",
    noShowHint: "تم تحرير الكرسي تلقائياً. يلزم التواصل مع صاحب الحجز ثم إغلاق التنبيه.",
    noShowResolve: "تمت المعالجة",
    noShowResolvePrompt: "ماذا حدث؟ (اختياري)",
    noShowNote: "ملاحظة المعالجة",
    noShowSubtitle: "تنبيهات لم تُغلق بعد، من أي تاريخ",
    noShowEmpty: "لا توجد تنبيهات مفتوحة.",
    noShowPending: (n: number) => `${n} بانتظار المعالجة`,
    noShowReview: "عرضها",
    noShowChoose: "كيف تمت المعالجة؟",
    noShowRescheduleHint: "اختيار موعد جديد — يعود الحجز إلى «مؤكد».",
    noShowCancelIt: "تسجيل السبب وإلغاء الحجز",
    noShowCancelHint: "يُغلق التنبيه ويصبح الحجز ملغياً.",
    noShowReasonLabel: "سبب عدم الحضور",
    noShowTabOpen: "مفتوحة",
    noShowTabResolved: "تمت معالجتها",
    noShowResolvedOn: "عولجت في",
    noShowNoneResolved: "لم تُعالَج أي حالة بعد.",
    pendingHint: "الكرسي محجوز مؤقتاً ولم يتم الدفع بعد.",
    reviewTitle: "تقييم العميل",
    reviewService: "الخدمة",
    reviewTech: "الفنية",
    reviewSkipped: "لم تُقيَّم",
    reviewWaiting: "أُرسلت الدعوة، بانتظار الرد",
    reviewNotInvited: "لم تُرسل دعوة تقييم لهذا الحجز.",
    reviewNoComment: "بدون ملاحظة",
    statuses: {
      pending: "بانتظار التأكيد",
      confirmed: "مؤكد",
      checked_in: "بانتظار الفنية",
      in_progress: "جارٍ التنفيذ",
      completed: "مكتمل",
      cancelled: "ملغي",
      no_show: "لم تحضر",
    },
    sources: { web: "الموقع", walk_in: "مباشر", phone: "هاتف" },
  },

  myDay: {
    title: "يومي",
    subtitle: "حجوزاتك اليوم",
    empty: "لا توجد حجوزات لك اليوم.",
    ticket: "التذكرة",
    station: "الكرسي",
    customer: "العميل",
    notes: "ملاحظات",
    design: "التصميم",
    confirmTicket: "يُرجى تأكيد رقم التذكرة مع العميل قبل البدء.",
    start: "بدء",
    finish: "إنهاء",
    waitingForDesk: "بانتظار إغلاق الاستقبال",
    elapsed: "المدة",
    expected: "المتوقع",
    done: "تم",
    totalWorked: "إجمالي وقت العمل",
    failed: "تعذّر التنفيذ، حدّثي الصفحة.",
    historyTitle: "الخدمات التي أنجزتِها",
    historyEmpty: "لم تنجزي أي خدمة خلال هذه الفترة.",
    nextUp: "التالية",
    laterToday: "لاحقاً اليوم",
    finishedCount: (n: number) => `منجزة · ${n}`,
    startsIn: (n: number) => `خلال ${n} دقيقة`,
    startsNow: "الآن",
    openDetail: "التفاصيل",
    arrivedTitle: "وصلت عميلتك",
    arrivedBody: (name: string) => `${name} في الاستقبال الآن.`,
    arrivedDismiss: "حسناً",
    waitingBadge: "بانتظارك",
    took: "استغرقت",
  },

  floor: {
    title: "طاقم اليوم",
    subtitle: "{n} فنية على رأس العمل اليوم",
    here: "موجودة",
    off: "غادرت",
    sendHome: "تسجيل مغادرة",
    bringBack: "إلغاء المغادرة",
    needsMoving: "حجوزات بحاجة إلى فنية أخرى",
    nothingToMove: "لا توجد حجوزات قادمة تحتاج إلى نقل.",
    staysWithHer: (n: number) =>
      `${n} حجز يبقى باسمها — خدمات منتهية أو عميل على الكرسي الآن`,
    moveTo: "نقل إلى…",
    needsTechnician: "حجوزات بدون فنية",
    sentHomeTitle: "حجوزات بحاجة إلى فنية الآن",
    sentHomeBody: (n: number) =>
      `${n} حجز فقد فنيته للتو، ولن يُعيَّن تلقائياً. اختر فنية لكل حجز قبل موعده.`,
    done: "تم",
    noTechnicians: "لا توجد فنيات في هذا الفرع",
    onLeave: "هذه إجازة مسجَّلة — تُعدَّل من صفحة الموظفين.",
  },

  frontDesk: {
    title: "الاستقبال",
    subtitle: "تسجيل الوصول برقم التذكرة",
    ticketLabel: "رقم التذكرة أو رقم الحجز",
    ticketPlaceholder: "A12  أو  RON-4F2K",
    search: "بحث",
    checkIn: "تسجيل الوصول",
    close: "إغلاق التذكرة",
    technician: "الفنية",
    autoAssigned: "تم التعيين تلقائياً",
    noneFree: "لا توجد فنية متاحة — يلزم الاختيار يدوياً",
    unassigned: "بدون تعيين — حجز لاحق",
    unassignedShort: "بدون تعيين",
    busySuffix: "مشغولة",
    offSuffix: "إجازة",
    changeTech: "تغيير الفنية",
    techLocked: "انتهت الخدمة — لا يمكن تغيير الفنية",
    techNoShow: "لم يحضر صاحب الحجز — لا يمكن تعيين فنية، يلزم حجز موعد جديد",
    techNoShowShort: "لم تحضر",
    took: "استغرقت",
    running: "جارية منذ",
    readyToClose: "جاهزة للإغلاق",
    today: "بقية حجوزات اليوم",
    statCompleted: "خدمات منتهية اليوم",
    statInService: "جارٍ تنفيذها الآن",
    statUpcoming: "حجوزات قادمة اليوم",
    statWaiting: "بانتظار تسجيل الوصول",
    notFound: "لا يوجد حجز بهذا الرقم اليوم في هذا الفرع.",
    notToday: "هذه التذكرة ليست لليوم.",
    alreadyIn: "تم تسجيل الوصول لهذا الحجز مسبقاً.",
    notCheckable: "لا يمكن تسجيل الوصول لهذه الحالة.",
    tooEarly: "مبكر — تسجيل الوصول يبدأ الساعة",
    partyWith: "معها في نفس الحجز",
    partyHint: "سجّلي وصول كل واحدة على حدة.",
    laneArriving: "تصل خلال ٣٠ دقيقة",
    laneLate: "متأخرة",
    laneInService: "جارية الآن",
    laneReady: "جاهزة للإغلاق",
    laneEmpty: "لا شيء هنا الآن.",
    notStarted: "بانتظار الفنية",
    minutesLate: (n: number) => `متأخرة ${n} دقيقة`,
    noShowIn: (n: number) => `تُسجّل كعدم حضور خلال ${n} دقيقة`,
    ofAbout: (n: number) => `من حوالي ${n}`,
    overBy: (n: number) => `تجاوزت ${n} دقيقة`,
    opensIn: "يفتح خلال",
    ticket: "التذكرة",
    booked: "الموعد",
    checkedIn: "سُجِّل الوصول",
    started: "بدأت",
    remaining: "المتبقي",
    detailTitle: "تفاصيل الحجز",
    visitCount: (n: number) => `الزيارة رقم ${n}`,
    firstVisit: "زيارتها الأولى",
    failed: "تعذّر التنفيذ، يُرجى المحاولة مرة أخرى.",
  },

  technicians: {
    title: "الفنيات",
    subtitle: "ما أنجزته كل فنية في اليوم، والوقت المستغرق في كل خدمة",
    noTechnicians: "لا توجد فنيات في هذا الفرع",
    noBookings: "لا توجد حجوزات في هذا اليوم.",
    booked: "حجوزات",
    done: "منتهية",
    inService: "جارية",
    noShow: "لم تحضر",
    minutesWorked: "دقيقة عمل",
    avgEach: "دقيقة للخدمة الواحدة",
  },

  performance: {
    title: "الأداء",
    subtitle: "أوقات التنفيذ لكل فنية — العمولة تُحتسب لاحقاً",
    technician: "الفنية",
    services: "الخدمات المنتهية",
    avgService: "متوسط مدة الخدمة",
    avgExpected: "مقابل المتوقع",
    avgWait: "متوسط الانتظار",
    noData: "لا توجد خدمات منتهية في هذه الفترة.",
    period7: "٧ أيام",
    period30: "٣٠ يوماً",
    periodToday: "اليوم",
    minutes: "دقيقة",
    faster: "أسرع",
    slower: "أبطأ",
    commissionNote:
      "المبالغ غير معروضة: قاعدة احتساب العمولة لم تُحدَّد بعد. هذه الأرقام هي أساسها.",
  },

  availability: {
    title: "أوقات العمل",
    subtitle: "ساعات الدوام والكراسي والإغلاقات — هذه تحدد المواعيد المتاحة",
    hours: "ساعات العمل",
    stations: "الكراسي",
    closures: "الإغلاقات",
    weekday: "اليوم",
    opens: "من",
    closes: "إلى",
    closed: "مغلق",
    addStation: "إضافة كرسي",
    stationLabel: "الاسم",
    qrCodes: "رموز QR للكراسي",
    addClosure: "إضافة إغلاق",
    from: "من تاريخ",
    to: "إلى تاريخ",
    reason: "السبب",
    noClosures: "لا توجد إغلاقات",
    weekdays: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"],
    saved: "تم الحفظ",
  },

  giftCards: {
    title: "بطاقات الهدايا",
    subtitle: "البطاقات المُصدرة وإعدادات القيم والتصاميم",
    tabIssued: "البطاقات المُصدرة",
    tabSetup: "الإعدادات",
    issue: "إصدار بطاقة",
    code: "الرمز",
    initial: "القيمة الأصلية",
    balance: "الرصيد",
    buyer: "المشترية",
    recipient: "المستلمة",
    status: "الحالة",
    expires: "تنتهي في",
    issuedAt: "تاريخ الإصدار",
    empty: "لا توجد بطاقات مُصدرة",
    values: "القيم المتاحة",
    designs: "تصاميم البطاقة",
    addValue: "إضافة قيمة",
    amount: "المبلغ",
    ledger: "سجل الحركات",
    adjust: "تعديل الرصيد",
    adjustAmount: "المبلغ (سالب للخصم)",
    adjustReason: "السبب",
    noTxns: "لا توجد حركات",
    message: "الرسالة",
    cancelCard: "إلغاء البطاقة",
    insufficient: "الرصيد غير كافٍ",
    statuses: { active: "فعّالة", redeemed: "مستخدمة", expired: "منتهية", cancelled: "ملغاة" },
  },

  customers: {
    title: "العملاء",
    subtitle: "الملفات والسجل والملاحظات",
    search: "بحث بالاسم أو رقم الجوال",
    name: "الاسم",
    phone: "رقم الجوال",
    email: "البريد الإلكتروني",
    bookingsCount: "عدد الحجوزات",
    lifetime: "إجمالي الإنفاق",
    lastVisit: "آخر زيارة",
    notes: "ملاحظات داخلية",
    blocked: "محظورة",
    blockedHint: "لا يمكنها الحجز عبر الموقع",
    history: "سجل الحجوزات",
    noHistory: "لا توجد حجوزات",
    noShows: "مرات عدم الحضور",
    empty: "لا توجد عميلات بعد",
    never: "لا يوجد",
  },

  staff: {
    title: "الموظفون",
    subtitle: "الحسابات والصلاحيات",
    invite: "إضافة موظف",
    edit: "تعديل الموظف",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "رقم الجوال",
    role: "الصلاحية",
    branch: "الفرع",
    allBranches: "كل الفروع",
    pickBranch: "اختيار الفرع",
    branchRequired: "لا بد من تحديد فرع لموظفي الاستقبال والفنيات",
    password: "كلمة المرور",
    passwordHint: "8 أحرف على الأقل — اتركيه فارغاً لعدم التغيير",
    passwordRequired: "كلمة المرور مطلوبة للحساب الجديد",
    active: "نشط",
    lastLogin: "آخر دخول",
    never: "لم يسجل الدخول",
    empty: "لا يوجد موظفون",
    emailTaken: "هذا البريد مستخدم بالفعل",
    cannotEscalate: "لا يمكنك منح صلاحية أعلى من صلاحيتك",
    lastCeo: "لا يمكن تعطيل آخر حساب رئيس تنفيذي",
    self: "أنت",
    deleteConfirm: "حذف هذا الحساب؟",
    daysOff: "أيام الإجازة",
    daysOffHint: "لا يتم توزيع حجوزات هذه الأيام على هذه الفنية.",
    from: "من",
    to: "إلى",
    addDayOff: "إضافة إجازة",
    removeDayOff: "حذف الإجازة",
    noDaysOff: "لا توجد إجازات مسجلة",
    badRange: "تاريخ النهاية قبل تاريخ البداية",
  },

  media: {
    title: "مكتبة الصور",
    subtitle: "كل الصور المستخدمة في الموقع",
    upload: "رفع صورة",
    choose: "اختيار صورة",
    change: "تغيير",
    remove: "إزالة الصورة",
    empty: "لا توجد صور بعد",
    hint: "WebP أو PNG أو JPEG · بحد أقصى 5 ميجابايت",
    badType: "صيغة غير مدعومة",
    tooLarge: "حجم الملف أكبر من 5 ميجابايت",
    uploadFailed: "فشل الرفع، حاول مرة أخرى",
    deleteConfirm: "حذف هذه الصورة؟",
    inUse: "مستخدمة",
    dimensions: "الأبعاد",
    size: "الحجم",
    localDriver:
      "التخزين المحلي قيد الاستخدام — الصور تُحفظ في مجلد المشروع. اضبط مفاتيح Supabase قبل النشر.",
  },

  catalog: {
    title: "الخدمات والإضافات",
    subtitle: "الأسعار والمدد والصور التي تظهر في صفحة الحجز",
    tabServices: "الخدمات",
    tabAddons: "الإضافات",
    tabRemovals: "الإزالة",
    newService: "خدمة جديدة",
    newAddon: "إضافة جديدة",
    newRemoval: "نوع إزالة جديد",
    editService: "تعديل الخدمة",
    editAddon: "تعديل الإضافة",
    editRemoval: "تعديل نوع الإزالة",
    designs: "التصاميم",
    addDesign: "إضافة تصميم",
    designsHint: "الصور التي تظهر للعميل عند اختيار هذه الإضافة. أضف اسماً وصورة لكل تصميم.",
    nameAr: "الاسم (عربي)",
    nameEn: "الاسم (إنجليزي)",
    descAr: "الوصف (عربي)",
    descEn: "الوصف (إنجليزي)",
    price: "السعر",
    duration: "المدة (دقيقة)",
    durationHint: "تُستخدم لحساب المواعيد المتاحة",
    hasRefill: "هذه الخدمة لها إعادة تعبئة",
    hasRefillHint: "يظهر زر إعادة التعبئة في حجوزات العميل خلال المهلة المحددة، بسعر مخفَّض.",
    refillDays: "مدة المهلة (أيام)",
    refillDaysHint: "الأظافر ٣٠ يوماً، الرموش ١٤ عادةً. تُحسب من موعد الزيارة.",
    image: "الصورة",
    active: "مفعّلة",
    activeHint: "غير المفعّلة لا تظهر في الموقع",
    seasonal: "لها تصاميم",
    seasonalHint: "يختار العميل تصميماً من قائمة صور بعد اختيار هذه الإضافة",
    order: "الترتيب",
    copyFromAr: "نسخ من العربي",
    missingAr: "الاسم العربي مطابق للإنجليزي",
    saved: "تم الحفظ",
    deleteConfirm: "حذف هذا العنصر؟",
    delete: "حذف",
    inactive: "غير مفعّلة",
    empty: "لا توجد عناصر",
    minutes: "دقيقة",
    inUseCannotDelete: "لا يمكن الحذف: العنصر مرتبط بحجوزات سابقة. عطّله بدلاً من ذلك.",
  },

  reviews: {
    title: "التقييمات",
    subtitle: "تقييم العملاء بعد إنهاء التذكرة.",
    avgService: "متوسط تقييم الخدمة",
    avgTech: "متوسط تقييم الفنية",
    outOfFive: "من ٥",
    noTechYet: "لم يتم ربط الحجوزات بالفنيات بعد",
    responseRate: "نسبة الاستجابة",
    ofInvited: (answered: number, invited: number) => `${answered} من ${invited} دعوة`,
    when: "الموعد",
    service: "الخدمة",
    technician: "الفنية",
    serviceScore: "الخدمة",
    techScore: "الفنية",
    comment: "الملاحظة",
    pending: "بانتظار الرد",
    skipped: "لم تُقيَّم",
    empty: "لا توجد تقييمات بعد",
    emptyBody: "تُرسل دعوة التقييم تلقائياً عند إنهاء التذكرة.",
  },

  promoCodes: {
    title: "أكواد الخصم",
    subtitle: "أكواد المناسبات — اليوم الوطني، العيد، وغيرها.",
    newCode: "كود جديد",
    editCode: "تعديل الكود",
    code: "الكود",
    codeHint: "حروف وأرقام فقط، بدون مسافات.",
    type: "نوع الخصم",
    percent: "نسبة",
    fixed: "مبلغ ثابت",
    percentValue: "النسبة ٪",
    percentHint: "من ١ إلى ١٠٠",
    fixedValue: "المبلغ (ر.س)",
    discount: "الخصم",
    minTotal: "الحد الأدنى للفاتورة",
    minTotalHint: "صفر يعني بدون حد أدنى.",
    startsAt: "يبدأ",
    endsAt: "ينتهي",
    always: "بدون مدة",
    window: "المدة",
    maxUses: "الحد الأقصى للاستخدام",
    maxUsesHint: "اتركيه فارغاً لاستخدام غير محدود.",
    used: "الاستخدام",
    activeLabel: "مُفعّل",
    inactive: "موقوف",
    activate: "تفعيل",
    deactivate: "إيقاف",
    sar: "ر.س",
    empty: "لا توجد أكواد خصم",
    emptyBody: "أنشئي كوداً ليظهر للعميلة في صفحة الدفع.",
    errors: {
      duplicate: "هذا الكود موجود مسبقاً",
      "code-format": "الكود يجب أن يكون حروفاً وأرقاماً فقط",
      "percent-range": "النسبة يجب أن تكون ١٠٠ أو أقل",
      "bad-window": "تاريخ الانتهاء يجب أن يكون بعد تاريخ البدء",
      "not-found": "لم يعد هذا الكود موجوداً",
      invalid: "تحققي من الحقول",
      failed: "حدث خطأ، حاول مرة أخرى",
    },
  },

  common: {
    loading: "جارٍ التحميل…",
    save: "حفظ",
    cancel: "إلغاء",
    soon: "قريباً",
    comingSoon: "هذا القسم قيد التطوير",
    none: "لا يوجد",
    riyal: "ر.س",
    add: "إضافة",
    edit: "تعديل",
    saving: "جارٍ الحفظ…",
    error: "حدث خطأ، حاول مرة أخرى",
    moveUp: "تحريك لأعلى",
    moveDown: "تحريك لأسفل",
  },
};

export type AdminStrings = typeof ar;

const en: AdminStrings = {
  brand: "Red Or Nude",
  panel: "Admin",

  nav: {
    dashboard: "Dashboard",
    bookings: "Bookings",
    noShows: "No-shows",
    frontDesk: "Front desk",
    floor: "Today's team",
    availability: "Availability",
    catalog: "Catalog",
    media: "Media",
    designs: "Designs",
    customers: "Customers",
    giftCards: "Gift cards",
    staff: "Staff",
    technicians: "Technicians",
    performance: "Performance",
    reviews: "Reviews",
    branches: "Branches",
    content: "Content",
    promoCodes: "Discount codes",
    marketing: "Marketing",
    settings: "Settings",
    auditLog: "Audit log",
  },

  groups: {
    operations: "Operations",
    catalogue: "Catalogue",
    people: "People",
    site: "Site",
    system: "System",
  },

  login: {
    title: "Sign in",
    subtitle: "Red Or Nude admin",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    invalid: "Incorrect email or password",
    error: "Could not sign in, please try again",
    staffOnly: "Staff only",
  },

  topbar: {
    allBranches: "All branches",
    branch: "Branch",
    signOut: "Sign out",
    search: "Search",
    account: "Account",
  },

  dashboard: {
    title: "Dashboard",
    welcome: "Welcome",
    todayBookings: "Today's bookings",
    upcoming: "Upcoming",
    revenueToday: "Revenue today",
    utilisation: "Chair utilisation",
    services: "Active services",
    customers: "Customers",
    denied: "You don't have access to that section",
    vsLastWeek: "vs last week",
    chairHours: (sold: number, total: number) => `${sold} of ${total} chair-hours sold`,
    hoursUnsold: (hours: number) => `${hours} hours unsold`,
    noShowsWeek: "No-shows this week",
    branchesToday: "Branches today",
    openBranch: "Tap a branch to open its day",
    topServices: "Top services today",
    byRevenue: "By revenue",
    techniciansToday: "Technicians today",
    doneAvg: "Done · avg",
    booked: (n: number) => `${n} booked`,
    techniciansIn: (n: number) => `${n} technicians in`,
    needsYou: "Needs you",
    allQuiet: "Nothing needs you right now.",
    unassigned: "Bookings with no technician",
    lowReview: (rating: number) => `${rating}-star review`,
    onLeave: "On leave",
    assign: "Assign",
  },

  audit: {
    title: "Audit log",
    subtitle: "Every change to prices and bookings is recorded here",
    actor: "User",
    action: "Action",
    entity: "Entity",
    when: "When",
    changes: "Changes",
    empty: "No activity recorded yet",
  },

  bookings: {
    title: "Bookings",
    onThisDay: "on this day",
    walkIn: "Walk-in",
    create: "Create booking",
    dayView: "Day",
    listView: "List",
    prevDay: "Previous day",
    nextDay: "Next day",
    date: "Date",
    jumpToday: "Today",
    station: "Chair",
    time: "Time",
    customer: "Customer",
    phone: "Mobile",
    service: "Service",
    addons: "Add-ons",
    removal: "Removal",
    status: "Status",
    total: "Total",
    code: "Reference",
    refillOf: "Refill of",
    refillDays: "Days",
    source: "Source",
    notes: "Notes",
    empty: "No bookings on this day",
    noStations: "No chairs set up for this branch",
    noStationsBody: "Add chairs on the Availability page before this branch can take bookings.",
    noSlots: "No times available",
    pickTime: "Pick a time",
    slotTaken: "That time was just taken, choose another",
    changeStatus: "Change status",
    reschedule: "Change time",
    rescheduleOn: "Day",
    rescheduleCurrent: "Currently",
    rescheduled: "Appointment moved.",
    del: "Delete booking",
    delConfirm: "Delete this booking for good? This cannot be undone. To end a real appointment, cancel it instead.",
    delConfirmGroup: (n: number) => `This deletes all ${n} bookings — the whole group. It cannot be undone.`,
    delHasPayment: "A paid booking can't be deleted. Cancel it instead.",
    delHasReview: "This booking has a customer review and can't be deleted.",
    delHasPoints: "This booking earned or spent loyalty points and can't be deleted.",
    group: "Group booking",
    groupOf: (letter: string, n: number) => `Group ${letter} · ${n}`,
    groupLetter: (letter: string) => `Group ${letter}`,
    groupWith: "Booked with",
    groupNote: "Booked together — one bill, and they arrive together.",
    tabBooked: "Booked",
    tabDropped: "Cancelled & no-show",
    droppedEmpty: "Nothing was cancelled or missed on this day.",
    pageOf: (from: number, to: number, total: number) => `${from}–${to} of ${total}`,
    prevPage: "Previous",
    nextPage: "Next",
    cancelReason: "Reason for cancelling (optional)",
    optional: "Optional",
    checkIn: "Check in",
    noShowTitle: "Nobody checked in",
    noShowHint: "The chair was released automatically. Sort the booking out, then close this.",
    noShowResolve: "Resolve",
    noShowResolvePrompt: "What happened? (optional)",
    noShowNote: "Resolution note",
    noShowSubtitle: "Flags nobody has closed yet, from any date",
    noShowEmpty: "Nothing outstanding.",
    noShowPending: (n: number) => `${n} waiting to be resolved`,
    noShowReview: "Review",
    noShowChoose: "How was this settled?",
    noShowRescheduleHint: "Pick a new time. The booking goes back to confirmed.",
    noShowCancelIt: "Record a reason and cancel",
    noShowCancelHint: "Closes the flag and marks the booking cancelled.",
    noShowReasonLabel: "Reason for the no-show",
    noShowTabOpen: "Open",
    noShowTabResolved: "Resolved",
    noShowResolvedOn: "Resolved",
    noShowNoneResolved: "Nothing has been resolved yet.",
    pendingHint: "Chair is held — not paid for yet.",
    reviewTitle: "Customer rating",
    reviewService: "Service",
    reviewTech: "Technician",
    reviewSkipped: "Skipped",
    reviewWaiting: "Invitation sent, no answer yet",
    reviewNotInvited: "No rating invitation was created for this booking.",
    reviewNoComment: "No note left",
    statuses: {
      pending: "Pending",
      confirmed: "Confirmed",
      checked_in: "Waiting for technician",
      in_progress: "In progress",
      completed: "Completed",
      cancelled: "Cancelled",
      no_show: "No-show",
    },
    sources: { web: "Website", walk_in: "Walk-in", phone: "Phone" },
  },

  myDay: {
    title: "My day",
    subtitle: "Your bookings today",
    empty: "Nothing booked for you today.",
    ticket: "Ticket",
    station: "Chair",
    customer: "Customer",
    notes: "Notes",
    design: "Design",
    confirmTicket: "Confirm the ticket number with the customer before you start.",
    start: "Start",
    finish: "Finish",
    waitingForDesk: "Waiting for the front desk to close it",
    elapsed: "Elapsed",
    expected: "Expected",
    done: "Done",
    totalWorked: "Total time worked",
    failed: "That didn't go through — refresh and try again.",
    historyTitle: "Services you've finished",
    historyEmpty: "You haven't finished any services in this period.",
    nextUp: "Next up",
    laterToday: "Later today",
    finishedCount: (n: number) => `Finished · ${n}`,
    startsIn: (n: number) => `in ${n} min`,
    startsNow: "Now",
    openDetail: "Details",
    arrivedTitle: "Your customer has arrived",
    arrivedBody: (name: string) => `${name} is at the front desk now.`,
    arrivedDismiss: "Got it",
    waitingBadge: "Waiting for you",
    took: "Took",
  },

  floor: {
    title: "Today's team",
    subtitle: "{n} technician(s) working today",
    here: "Here",
    off: "Gone home",
    sendHome: "Send home",
    bringBack: "Bring back",
    needsMoving: "Bookings that need another technician",
    nothingToMove: "Nothing still ahead to move.",
    staysWithHer: (n: number) =>
      `${n} stay with her — already finished, or a customer in the chair now`,
    moveTo: "Move to…",
    needsTechnician: "Bookings with no technician",
    sentHomeTitle: "These bookings need a technician now",
    sentHomeBody: (n: number) =>
      `${n} booking(s) just lost their technician, and none is assigned automatically. Pick one for each before its appointment time.`,
    done: "Done",
    noTechnicians: "No technicians at this branch",
    onLeave: "That is booked leave — change it under Staff.",
  },

  frontDesk: {
    title: "Front desk",
    subtitle: "Check a customer in by ticket number",
    ticketLabel: "Ticket or booking number",
    ticketPlaceholder: "A12  or  RON-4F2K",
    search: "Find",
    checkIn: "Check in",
    close: "Close ticket",
    technician: "Technician",
    autoAssigned: "Assigned automatically",
    noneFree: "Nobody free — pick someone by hand",
    unassigned: "Unassigned — booked later today",
    unassignedShort: "Unassigned",
    busySuffix: "busy",
    offSuffix: "off",
    changeTech: "Change technician",
    techLocked: "Service finished — technician can't be changed",
    techNoShow: "Customer didn't show — no technician to assign, a new appointment is needed",
    techNoShowShort: "Didn't show",
    took: "Took",
    running: "Running for",
    readyToClose: "Ready to close",
    // Not today — today is the four lanes above. This is what they left behind:
    // later appointments, plus the day's closed, cancelled and no-show rows.
    today: "Everything else today",
    statCompleted: "Finished today",
    statInService: "In service now",
    statUpcoming: "Still to come today",
    statWaiting: "Waiting to check in",
    notFound: "No booking with that number today at this branch.",
    notToday: "That ticket isn't for today.",
    alreadyIn: "This customer is already checked in.",
    notCheckable: "This booking can't be checked in.",
    tooEarly: "Early — check-in opens at",
    partyWith: "With her on this booking",
    partyHint: "Check each of them in separately.",
    laneArriving: "Arriving next 30 min",
    laneLate: "Late",
    laneInService: "In service",
    laneReady: "Ready to close",
    laneEmpty: "Nothing here right now.",
    notStarted: "Waiting for technician",
    minutesLate: (n: number) => `${n} min late`,
    noShowIn: (n: number) => `no-show in ${n} min`,
    ofAbout: (n: number) => `of about ${n}`,
    overBy: (n: number) => `${n} min over`,
    opensIn: "opens in",
    ticket: "Ticket",
    booked: "Booked",
    checkedIn: "Checked in",
    started: "Started",
    remaining: "Remaining",
    detailTitle: "Booking detail",
    visitCount: (n: number) => `${n}th visit`,
    firstVisit: "First visit",
    failed: "That didn't go through — try again.",
  },

  technicians: {
    title: "Technicians",
    subtitle: "What each technician finished that day, and how long each service took",
    noTechnicians: "No technicians at this branch",
    noBookings: "No bookings on this day.",
    booked: "Booked",
    done: "Finished",
    inService: "In service",
    noShow: "No-show",
    minutesWorked: "min worked",
    avgEach: "min per service",
  },

  performance: {
    title: "Performance",
    subtitle: "How long each technician takes — commission is calculated later",
    technician: "Technician",
    services: "Services finished",
    avgService: "Average service time",
    avgExpected: "Against expected",
    avgWait: "Average wait",
    noData: "No finished services in this period.",
    period7: "7 days",
    period30: "30 days",
    periodToday: "Today",
    minutes: "min",
    faster: "faster",
    slower: "slower",
    commissionNote:
      "No money shown: the commission rule hasn't been set yet. These are the numbers it will be based on.",
  },

  availability: {
    title: "Availability",
    subtitle: "Opening hours, chairs and closures — these determine what can be booked",
    hours: "Opening hours",
    stations: "Chairs",
    closures: "Closures",
    weekday: "Day",
    opens: "Opens",
    closes: "Closes",
    closed: "Closed",
    addStation: "Add chair",
    stationLabel: "Label",
    qrCodes: "Chair QR codes",
    addClosure: "Add closure",
    from: "From",
    to: "To",
    reason: "Reason",
    noClosures: "No closures",
    weekdays: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    saved: "Saved",
  },

  giftCards: {
    title: "Gift cards",
    subtitle: "Issued cards, plus the values and designs offered on the site",
    tabIssued: "Issued",
    tabSetup: "Setup",
    issue: "Issue card",
    code: "Code",
    initial: "Initial value",
    balance: "Balance",
    buyer: "Buyer",
    recipient: "Recipient",
    status: "Status",
    expires: "Expires",
    issuedAt: "Issued",
    empty: "No cards issued yet",
    values: "Available values",
    designs: "Card designs",
    addValue: "Add value",
    amount: "Amount",
    ledger: "Transactions",
    adjust: "Adjust balance",
    adjustAmount: "Amount (negative to deduct)",
    adjustReason: "Reason",
    noTxns: "No transactions",
    message: "Message",
    cancelCard: "Cancel card",
    insufficient: "Insufficient balance",
    statuses: { active: "Active", redeemed: "Redeemed", expired: "Expired", cancelled: "Cancelled" },
  },

  customers: {
    title: "Customers",
    subtitle: "Profiles, history and notes",
    search: "Search by name or mobile",
    name: "Name",
    phone: "Mobile",
    email: "Email",
    bookingsCount: "Bookings",
    lifetime: "Lifetime value",
    lastVisit: "Last visit",
    notes: "Internal notes",
    blocked: "Blocked",
    blockedHint: "Cannot book through the website",
    history: "Booking history",
    noHistory: "No bookings",
    noShows: "No-shows",
    empty: "No customers yet",
    never: "Never",
  },

  staff: {
    title: "Staff",
    subtitle: "Accounts and permissions",
    invite: "Add staff",
    edit: "Edit staff",
    name: "Name",
    email: "Email",
    phone: "Mobile",
    role: "Role",
    branch: "Branch",
    allBranches: "All branches",
    pickBranch: "Choose a branch",
    branchRequired: "A receptionist or technician must belong to one branch",
    password: "Password",
    passwordHint: "At least 8 characters — leave blank to keep unchanged",
    passwordRequired: "A password is required for a new account",
    active: "Active",
    lastLogin: "Last sign-in",
    never: "Never signed in",
    empty: "No staff accounts",
    emailTaken: "That email is already in use",
    cannotEscalate: "You cannot grant a role higher than your own",
    lastCeo: "The last CEO account cannot be deactivated",
    self: "You",
    deleteConfirm: "Delete this account?",
    daysOff: "Days off",
    daysOffHint: "No bookings are assigned on these days.",
    from: "From",
    to: "To",
    addDayOff: "Add days off",
    removeDayOff: "Remove these days off",
    noDaysOff: "No days off recorded",
    badRange: "The end date is before the start date",
  },

  media: {
    title: "Media library",
    subtitle: "Every image used across the site",
    upload: "Upload",
    choose: "Choose image",
    change: "Change",
    remove: "Remove image",
    empty: "No images yet",
    hint: "WebP, PNG or JPEG · 5 MB max",
    badType: "Unsupported file type",
    tooLarge: "File is larger than 5 MB",
    uploadFailed: "Upload failed, please try again",
    deleteConfirm: "Delete this image?",
    inUse: "In use",
    dimensions: "Dimensions",
    size: "Size",
    localDriver:
      "Using local storage — uploads are written into the project folder. Set the Supabase keys before deploying.",
  },

  catalog: {
    title: "Services & add-ons",
    subtitle: "Prices, durations and images shown on the booking page",
    tabServices: "Services",
    tabAddons: "Add-ons",
    tabRemovals: "Removal",
    newService: "New service",
    newAddon: "New add-on",
    newRemoval: "New removal type",
    editService: "Edit service",
    editAddon: "Edit add-on",
    editRemoval: "Edit removal type",
    designs: "Designs",
    addDesign: "Add design",
    designsHint: "The pictures a customer sees after choosing this add-on. Give each one a name and an image.",
    nameAr: "Name (Arabic)",
    nameEn: "Name (English)",
    descAr: "Description (Arabic)",
    descEn: "Description (English)",
    price: "Price",
    duration: "Duration (minutes)",
    durationHint: "Used to work out available appointment slots",
    hasRefill: "This service has a refill",
    hasRefillHint: "A refill button appears in the customer's bookings for the window below, at a discount.",
    refillDays: "Window length (days)",
    refillDaysHint: "Nails 30, lashes 14 typically. Counted from the appointment.",
    image: "Image",
    active: "Active",
    activeHint: "Inactive items are hidden from the site",
    seasonal: "Has designs",
    seasonalHint: "The customer picks a design from a grid of pictures after choosing this add-on",
    order: "Order",
    copyFromAr: "Copy from Arabic",
    missingAr: "Arabic name is the same as English",
    saved: "Saved",
    deleteConfirm: "Delete this item?",
    delete: "Delete",
    inactive: "Inactive",
    empty: "Nothing here yet",
    minutes: "min",
    inUseCannotDelete: "Can't delete: this item is attached to past bookings. Deactivate it instead.",
  },

  reviews: {
    title: "Reviews",
    subtitle: "What customers said after their ticket was ended.",
    avgService: "Average service rating",
    avgTech: "Average technician rating",
    outOfFive: "out of 5",
    noTechYet: "Bookings aren't assigned to technicians yet",
    responseRate: "Response rate",
    ofInvited: (answered: number, invited: number) => `${answered} of ${invited} invited`,
    when: "Appointment",
    service: "Service",
    technician: "Technician",
    serviceScore: "Service",
    techScore: "Technician",
    comment: "Note",
    pending: "Not answered",
    skipped: "Skipped",
    empty: "No reviews yet",
    emptyBody: "The invitation is sent automatically when a ticket is ended.",
  },

  promoCodes: {
    title: "Discount codes",
    subtitle: "Occasion codes — National Day, Eid, and whatever runs next.",
    newCode: "New code",
    editCode: "Edit code",
    code: "Code",
    codeHint: "Letters and digits only, no spaces.",
    type: "Discount type",
    percent: "Percentage",
    fixed: "Fixed amount",
    percentValue: "Percentage %",
    percentHint: "1 to 100",
    fixedValue: "Amount (SAR)",
    discount: "Discount",
    minTotal: "Minimum bill",
    minTotalHint: "Zero means no minimum.",
    startsAt: "Starts",
    endsAt: "Ends",
    always: "No window",
    window: "Window",
    maxUses: "Maximum uses",
    maxUsesHint: "Leave empty for unlimited.",
    used: "Used",
    activeLabel: "Active",
    inactive: "Off",
    activate: "Activate",
    deactivate: "Turn off",
    sar: "SAR",
    empty: "No discount codes",
    emptyBody: "Create one and it appears in the customer's checkout.",
    errors: {
      duplicate: "That code already exists",
      "code-format": "Codes must be letters and digits only",
      "percent-range": "A percentage can't be over 100",
      "bad-window": "The end date must be after the start date",
      "not-found": "That code no longer exists",
      invalid: "Check the fields",
      failed: "Something went wrong, please try again",
    },
  },

  common: {
    loading: "Loading…",
    save: "Save",
    cancel: "Cancel",
    soon: "Soon",
    comingSoon: "This section is under construction",
    none: "None",
    riyal: "SAR",
    add: "Add",
    edit: "Edit",
    saving: "Saving…",
    error: "Something went wrong, please try again",
    moveUp: "Move up",
    moveDown: "Move down",
  },
};

export const adminStrings = { ar, en } as const;
export type AdminLang = keyof typeof adminStrings;
