// Admin UI copy. The panel itself is bilingual — staff read Arabic — and flips
// dir like the public site. Same discipline as lib/dictionary.ts: `en` is
// type-checked against the `ar` shape, so a missing translation is a build error.

const ar = {
  brand: "ريد أور نيود",
  panel: "لوحة التحكم",

  nav: {
    dashboard: "الرئيسية",
    bookings: "الحجوزات",
    availability: "أوقات العمل",
    catalog: "الخدمات",
    media: "مكتبة الصور",
    designs: "التصاميم",
    customers: "العميلات",
    giftCards: "بطاقات الهدايا",
    staff: "الموظفون",
    performance: "الأداء",
    reviews: "التقييمات",
    branches: "الفروع",
    content: "المحتوى",
    promoCodes: "أكواد الخصم",
    marketing: "التسويق",
    settings: "الإعدادات",
    auditLog: "سجل النشاط",
  },

  groups: {
    operations: "العمليات",
    catalogue: "الكتالوج",
    people: "الأشخاص",
    site: "الموقع",
    system: "النظام",
  },

  login: {
    title: "تسجيل الدخول",
    subtitle: "لوحة تحكم ريد أور نيود",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    submit: "دخول",
    submitting: "جارٍ الدخول…",
    invalid: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    error: "تعذر تسجيل الدخول، حاول مرة أخرى",
    staffOnly: "هذه الصفحة للموظفين فقط",
  },

  topbar: {
    allBranches: "كل الفروع",
    branch: "الفرع",
    signOut: "تسجيل الخروج",
    search: "بحث",
    account: "الحساب",
  },

  dashboard: {
    title: "الرئيسية",
    welcome: "أهلاً",
    todayBookings: "حجوزات اليوم",
    upcoming: "المواعيد القادمة",
    revenueToday: "إيرادات اليوم",
    utilisation: "نسبة الإشغال",
    services: "الخدمات المفعّلة",
    customers: "العميلات",
    setupTitle: "الخطوات التالية",
    setupBody:
      "الأساس جاهز: قاعدة البيانات، الصلاحيات، وسجل النشاط. الوحدات التشغيلية تُبنى في المراحل التالية.",
    denied: "لا تملك صلاحية الوصول إلى هذا القسم",
  },

  audit: {
    title: "سجل النشاط",
    subtitle: "كل تعديل على الأسعار والحجوزات يُسجَّل هنا",
    actor: "المستخدم",
    action: "الإجراء",
    entity: "العنصر",
    when: "التاريخ",
    changes: "التغييرات",
    empty: "لا يوجد نشاط مسجل بعد",
  },

  bookings: {
    title: "الحجوزات",
    onThisDay: "حجز في هذا اليوم",
    walkIn: "حجز مباشر",
    create: "إنشاء الحجز",
    dayView: "اليوم",
    listView: "قائمة",
    prevDay: "اليوم السابق",
    nextDay: "اليوم التالي",
    station: "كرسي",
    time: "الوقت",
    customer: "العميلة",
    phone: "رقم الجوال",
    service: "الخدمة",
    addons: "الإضافات",
    removal: "الإزالة",
    status: "الحالة",
    total: "الإجمالي",
    code: "رقم الحجز",
    refillOf: "إعادة تعبئة لحجز",
    refillGrant: "منح إعادة تعبئة",
    refillGrantHint: "عدد الأيام من اليوم — يتجاوز مهلة الخدمة الافتراضية.",
    refillGrantedUntil: "إعادة التعبئة متاحة حتى",
    refillRevoke: "إلغاء المنح",
    refillDays: "الأيام",
    refillSaved: "تم تحديث مهلة إعادة التعبئة",
    source: "المصدر",
    notes: "ملاحظات",
    empty: "لا توجد حجوزات في هذا اليوم",
    noStations: "لا توجد كراسي معرّفة لهذا الفرع",
    noStationsBody: "أضيفي الكراسي من صفحة أوقات العمل حتى يمكن استقبال الحجوزات.",
    noSlots: "لا توجد مواعيد متاحة",
    pickTime: "اختاري الوقت",
    slotTaken: "تم حجز هذا الوقت للتو، اختاري وقتاً آخر",
    changeStatus: "تغيير الحالة",
    cancelReason: "سبب الإلغاء (اختياري)",
    optional: "اختياري",
    // The action that marks arrival. The *badge* still reads "جارٍ التنفيذ" —
    // only the button is renamed, because pressing it is now what the 20-minute
    // no-show rule measures, and "تسجيل الحضور" says that and "بدء" does not.
    checkIn: "تسجيل الحضور",
    noShowTitle: "حجوزات لم يحضر أصحابها",
    noShowHint: "تم تحرير الكرسي تلقائياً. تواصلي مع العميلة ثم أغلقي التنبيه.",
    noShowResolve: "تمت المعالجة",
    noShowResolvePrompt: "ماذا حدث؟ (اختياري)",
    noShowNote: "ملاحظة المعالجة",
    pendingHint: "الكرسي محجوز مؤقتاً ولم يتم الدفع بعد.",
    reviewTitle: "تقييم العميلة",
    reviewService: "الخدمة",
    reviewTech: "الفنية",
    reviewSkipped: "لم تُقيَّم",
    reviewWaiting: "أُرسلت الدعوة، بانتظار الرد",
    reviewNotInvited: "لم تُرسل دعوة تقييم لهذا الحجز.",
    reviewNoComment: "بدون ملاحظة",
    statuses: {
      pending: "بانتظار التأكيد",
      confirmed: "مؤكد",
      checked_in: "بانتظار الفنية",
      in_progress: "جارٍ التنفيذ",
      completed: "مكتمل",
      cancelled: "ملغي",
      no_show: "لم تحضر",
    },
    sources: { web: "الموقع", walk_in: "مباشر", phone: "هاتف" },
  },

  myDay: {
    title: "يومي",
    subtitle: "حجوزاتك اليوم",
    empty: "لا توجد حجوزات لك اليوم.",
    ticket: "التذكرة",
    station: "الكرسي",
    customer: "العميلة",
    notes: "ملاحظات",
    design: "التصميم",
    confirmTicket: "أكّدي رقم التذكرة مع العميلة قبل البدء.",
    start: "بدء",
    finish: "إنهاء",
    waitingForDesk: "بانتظار إغلاق الاستقبال",
    elapsed: "المدة",
    expected: "المتوقع",
    done: "تم",
    totalWorked: "إجمالي وقت العمل",
    failed: "تعذّر التنفيذ، حدّثي الصفحة.",
  },

  frontDesk: {
    title: "الاستقبال",
    subtitle: "سجّلي وصول العميلة برقم التذكرة",
    ticketLabel: "رقم التذكرة أو رقم الحجز",
    ticketPlaceholder: "A12  أو  RON-4F2K",
    search: "بحث",
    checkIn: "تسجيل الوصول",
    close: "إغلاق التذكرة",
    technician: "الفنية",
    autoAssigned: "تم التعيين تلقائياً",
    noneFree: "لا توجد فنية متاحة — اختاري واحدة يدوياً",
    changeTech: "تغيير الفنية",
    readyToClose: "جاهزة للإغلاق",
    today: "اليوم",
    statCompleted: "خدمات منتهية اليوم",
    statInService: "جارٍ تنفيذها الآن",
    statUpcoming: "حجوزات قادمة اليوم",
    statWaiting: "بانتظار تسجيل الوصول",
    notFound: "لا يوجد حجز بهذا الرقم اليوم في هذا الفرع.",
    notToday: "هذه التذكرة ليست لليوم.",
    alreadyIn: "تم تسجيل وصول هذه العميلة مسبقاً.",
    notCheckable: "لا يمكن تسجيل الوصول لهذه الحالة.",
    tooEarly: "وصلت مبكراً — تسجيل الوصول يبدأ الساعة",
    failed: "تعذّر التنفيذ، حاولي مرة أخرى.",
  },

  performance: {
    title: "الأداء",
    subtitle: "أوقات التنفيذ لكل فنية — العمولة تُحتسب لاحقاً",
    technician: "الفنية",
    services: "الخدمات المنتهية",
    avgService: "متوسط مدة الخدمة",
    avgExpected: "مقابل المتوقع",
    avgWait: "متوسط الانتظار",
    noData: "لا توجد خدمات منتهية في هذه الفترة.",
    period7: "٧ أيام",
    period30: "٣٠ يوماً",
    periodToday: "اليوم",
    minutes: "دقيقة",
    faster: "أسرع",
    slower: "أبطأ",
    commissionNote:
      "المبالغ غير معروضة: قاعدة احتساب العمولة لم تُحدَّد بعد. هذه الأرقام هي أساسها.",
  },

  availability: {
    title: "أوقات العمل",
    subtitle: "ساعات الدوام والكراسي والإغلاقات — هذه تحدد المواعيد المتاحة",
    hours: "ساعات العمل",
    stations: "الكراسي",
    closures: "الإغلاقات",
    weekday: "اليوم",
    opens: "من",
    closes: "إلى",
    closed: "مغلق",
    addStation: "إضافة كرسي",
    stationLabel: "الاسم",
    qrCodes: "رموز QR للكراسي",
    addClosure: "إضافة إغلاق",
    from: "من تاريخ",
    to: "إلى تاريخ",
    reason: "السبب",
    noClosures: "لا توجد إغلاقات",
    weekdays: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"],
    saved: "تم الحفظ",
  },

  giftCards: {
    title: "بطاقات الهدايا",
    subtitle: "البطاقات المُصدرة وإعدادات القيم والتصاميم",
    tabIssued: "البطاقات المُصدرة",
    tabSetup: "الإعدادات",
    issue: "إصدار بطاقة",
    code: "الرمز",
    initial: "القيمة الأصلية",
    balance: "الرصيد",
    buyer: "المشترية",
    recipient: "المستلمة",
    status: "الحالة",
    expires: "تنتهي في",
    issuedAt: "تاريخ الإصدار",
    empty: "لا توجد بطاقات مُصدرة",
    values: "القيم المتاحة",
    designs: "تصاميم البطاقة",
    addValue: "إضافة قيمة",
    amount: "المبلغ",
    ledger: "سجل الحركات",
    adjust: "تعديل الرصيد",
    adjustAmount: "المبلغ (سالب للخصم)",
    adjustReason: "السبب",
    noTxns: "لا توجد حركات",
    message: "الرسالة",
    cancelCard: "إلغاء البطاقة",
    insufficient: "الرصيد غير كافٍ",
    statuses: { active: "فعّالة", redeemed: "مستخدمة", expired: "منتهية", cancelled: "ملغاة" },
  },

  customers: {
    title: "العميلات",
    subtitle: "الملفات والسجل والملاحظات",
    search: "بحث بالاسم أو رقم الجوال",
    name: "الاسم",
    phone: "رقم الجوال",
    email: "البريد الإلكتروني",
    bookingsCount: "عدد الحجوزات",
    lifetime: "إجمالي الإنفاق",
    lastVisit: "آخر زيارة",
    notes: "ملاحظات داخلية",
    blocked: "محظورة",
    blockedHint: "لا يمكنها الحجز عبر الموقع",
    history: "سجل الحجوزات",
    noHistory: "لا توجد حجوزات",
    noShows: "مرات عدم الحضور",
    empty: "لا توجد عميلات بعد",
    never: "لا يوجد",
  },

  staff: {
    title: "الموظفون",
    subtitle: "الحسابات والصلاحيات",
    invite: "إضافة موظف",
    edit: "تعديل الموظف",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "رقم الجوال",
    role: "الصلاحية",
    branch: "الفرع",
    allBranches: "كل الفروع",
    password: "كلمة المرور",
    passwordHint: "8 أحرف على الأقل — اتركيه فارغاً لعدم التغيير",
    passwordRequired: "كلمة المرور مطلوبة للحساب الجديد",
    active: "نشط",
    lastLogin: "آخر دخول",
    never: "لم يسجل الدخول",
    empty: "لا يوجد موظفون",
    emailTaken: "هذا البريد مستخدم بالفعل",
    cannotEscalate: "لا يمكنك منح صلاحية أعلى من صلاحيتك",
    lastCeo: "لا يمكن تعطيل آخر حساب رئيس تنفيذي",
    self: "أنت",
    deleteConfirm: "حذف هذا الحساب؟",
  },

  media: {
    title: "مكتبة الصور",
    subtitle: "كل الصور المستخدمة في الموقع",
    upload: "رفع صورة",
    choose: "اختيار صورة",
    change: "تغيير",
    remove: "إزالة الصورة",
    empty: "لا توجد صور بعد",
    hint: "WebP أو PNG أو JPEG · بحد أقصى 5 ميجابايت",
    badType: "صيغة غير مدعومة",
    tooLarge: "حجم الملف أكبر من 5 ميجابايت",
    uploadFailed: "فشل الرفع، حاول مرة أخرى",
    deleteConfirm: "حذف هذه الصورة؟",
    inUse: "مستخدمة",
    dimensions: "الأبعاد",
    size: "الحجم",
    localDriver:
      "التخزين المحلي قيد الاستخدام — الصور تُحفظ في مجلد المشروع. اضبط مفاتيح Supabase قبل النشر.",
  },

  catalog: {
    title: "الخدمات والإضافات",
    subtitle: "الأسعار والمدد والصور التي تظهر في صفحة الحجز",
    tabServices: "الخدمات",
    tabAddons: "الإضافات",
    tabRemovals: "الإزالة",
    newService: "خدمة جديدة",
    newAddon: "إضافة جديدة",
    newRemoval: "نوع إزالة جديد",
    editService: "تعديل الخدمة",
    editAddon: "تعديل الإضافة",
    editRemoval: "تعديل نوع الإزالة",
    nameAr: "الاسم (عربي)",
    nameEn: "الاسم (إنجليزي)",
    descAr: "الوصف (عربي)",
    descEn: "الوصف (إنجليزي)",
    price: "السعر",
    duration: "المدة (دقيقة)",
    durationHint: "تُستخدم لحساب المواعيد المتاحة",
    refillDays: "مهلة إعادة التعبئة (أيام)",
    refillDaysHint: "٠ = لا توجد إعادة تعبئة. الأظافر ٣٠، الرموش ١٤. يظهر الزر في حجوزات العميلة خلال هذه المهلة فقط.",
    image: "الصورة",
    active: "مفعّلة",
    activeHint: "غير المفعّلة لا تظهر في الموقع",
    seasonal: "موسمية",
    seasonalHint: "تفتح نافذة التصاميم الموسمية",
    order: "الترتيب",
    copyFromAr: "نسخ من العربي",
    missingAr: "الاسم العربي مطابق للإنجليزي",
    saved: "تم الحفظ",
    deleteConfirm: "حذف هذا العنصر؟",
    delete: "حذف",
    inactive: "غير مفعّلة",
    empty: "لا توجد عناصر",
    minutes: "دقيقة",
    inUseCannotDelete: "لا يمكن الحذف: العنصر مرتبط بحجوزات سابقة. عطّله بدلاً من ذلك.",
  },

  reviews: {
    title: "التقييمات",
    subtitle: "تقييم العميلات بعد إنهاء التذكرة.",
    avgService: "متوسط تقييم الخدمة",
    avgTech: "متوسط تقييم الفنية",
    outOfFive: "من ٥",
    noTechYet: "لم يتم ربط الحجوزات بالفنيات بعد",
    responseRate: "نسبة الاستجابة",
    ofInvited: (answered: number, invited: number) => `${answered} من ${invited} دعوة`,
    when: "الموعد",
    service: "الخدمة",
    technician: "الفنية",
    serviceScore: "الخدمة",
    techScore: "الفنية",
    comment: "الملاحظة",
    pending: "بانتظار الرد",
    skipped: "لم تُقيَّم",
    empty: "لا توجد تقييمات بعد",
    emptyBody: "تُرسل دعوة التقييم تلقائياً عند إنهاء التذكرة.",
  },

  promoCodes: {
    title: "أكواد الخصم",
    subtitle: "أكواد المناسبات — اليوم الوطني، العيد، وغيرها.",
    newCode: "كود جديد",
    editCode: "تعديل الكود",
    code: "الكود",
    codeHint: "حروف وأرقام فقط، بدون مسافات.",
    type: "نوع الخصم",
    percent: "نسبة",
    fixed: "مبلغ ثابت",
    percentValue: "النسبة ٪",
    percentHint: "من ١ إلى ١٠٠",
    fixedValue: "المبلغ (ر.س)",
    discount: "الخصم",
    minTotal: "الحد الأدنى للفاتورة",
    minTotalHint: "صفر يعني بدون حد أدنى.",
    startsAt: "يبدأ",
    endsAt: "ينتهي",
    always: "بدون مدة",
    window: "المدة",
    maxUses: "الحد الأقصى للاستخدام",
    maxUsesHint: "اتركيه فارغاً لاستخدام غير محدود.",
    used: "الاستخدام",
    activeLabel: "مُفعّل",
    inactive: "موقوف",
    activate: "تفعيل",
    deactivate: "إيقاف",
    sar: "ر.س",
    empty: "لا توجد أكواد خصم",
    emptyBody: "أنشئي كوداً ليظهر للعميلة في صفحة الدفع.",
    errors: {
      duplicate: "هذا الكود موجود مسبقاً",
      "code-format": "الكود يجب أن يكون حروفاً وأرقاماً فقط",
      "percent-range": "النسبة يجب أن تكون ١٠٠ أو أقل",
      "bad-window": "تاريخ الانتهاء يجب أن يكون بعد تاريخ البدء",
      "not-found": "لم يعد هذا الكود موجوداً",
      invalid: "تحققي من الحقول",
      failed: "حدث خطأ، حاول مرة أخرى",
    },
  },

  common: {
    loading: "جارٍ التحميل…",
    save: "حفظ",
    cancel: "إلغاء",
    soon: "قريباً",
    comingSoon: "هذا القسم قيد التطوير",
    none: "لا يوجد",
    riyal: "ر.س",
    add: "إضافة",
    edit: "تعديل",
    saving: "جارٍ الحفظ…",
    error: "حدث خطأ، حاول مرة أخرى",
    moveUp: "تحريك لأعلى",
    moveDown: "تحريك لأسفل",
  },
};

export type AdminStrings = typeof ar;

const en: AdminStrings = {
  brand: "Red Or Nude",
  panel: "Admin",

  nav: {
    dashboard: "Dashboard",
    bookings: "Bookings",
    availability: "Availability",
    catalog: "Catalog",
    media: "Media",
    designs: "Designs",
    customers: "Customers",
    giftCards: "Gift cards",
    staff: "Staff",
    performance: "Performance",
    reviews: "Reviews",
    branches: "Branches",
    content: "Content",
    promoCodes: "Discount codes",
    marketing: "Marketing",
    settings: "Settings",
    auditLog: "Audit log",
  },

  groups: {
    operations: "Operations",
    catalogue: "Catalogue",
    people: "People",
    site: "Site",
    system: "System",
  },

  login: {
    title: "Sign in",
    subtitle: "Red Or Nude admin",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    invalid: "Incorrect email or password",
    error: "Could not sign in, please try again",
    staffOnly: "Staff only",
  },

  topbar: {
    allBranches: "All branches",
    branch: "Branch",
    signOut: "Sign out",
    search: "Search",
    account: "Account",
  },

  dashboard: {
    title: "Dashboard",
    welcome: "Welcome",
    todayBookings: "Today's bookings",
    upcoming: "Upcoming",
    revenueToday: "Revenue today",
    utilisation: "Utilisation",
    services: "Active services",
    customers: "Customers",
    setupTitle: "What's next",
    setupBody:
      "The foundation is in place: database, roles, and audit trail. Operational modules land in the phases that follow.",
    denied: "You don't have access to that section",
  },

  audit: {
    title: "Audit log",
    subtitle: "Every change to prices and bookings is recorded here",
    actor: "User",
    action: "Action",
    entity: "Entity",
    when: "When",
    changes: "Changes",
    empty: "No activity recorded yet",
  },

  bookings: {
    title: "Bookings",
    onThisDay: "on this day",
    walkIn: "Walk-in",
    create: "Create booking",
    dayView: "Day",
    listView: "List",
    prevDay: "Previous day",
    nextDay: "Next day",
    station: "Chair",
    time: "Time",
    customer: "Customer",
    phone: "Mobile",
    service: "Service",
    addons: "Add-ons",
    removal: "Removal",
    status: "Status",
    total: "Total",
    code: "Reference",
    refillOf: "Refill of",
    refillGrant: "Grant refill",
    refillGrantHint: "Days from today — overrides the service's own window.",
    refillGrantedUntil: "Refill available until",
    refillRevoke: "Revoke",
    refillDays: "Days",
    refillSaved: "Refill window updated",
    source: "Source",
    notes: "Notes",
    empty: "No bookings on this day",
    noStations: "No chairs set up for this branch",
    noStationsBody: "Add chairs on the Availability page before this branch can take bookings.",
    noSlots: "No times available",
    pickTime: "Pick a time",
    slotTaken: "That time was just taken, choose another",
    changeStatus: "Change status",
    cancelReason: "Reason for cancelling (optional)",
    optional: "Optional",
    checkIn: "Check in",
    noShowTitle: "Nobody checked in",
    noShowHint: "The chair was released automatically. Sort the customer out, then close this.",
    noShowResolve: "Resolve",
    noShowResolvePrompt: "What happened? (optional)",
    noShowNote: "Resolution note",
    pendingHint: "Chair is held — not paid for yet.",
    reviewTitle: "Customer rating",
    reviewService: "Service",
    reviewTech: "Technician",
    reviewSkipped: "Skipped",
    reviewWaiting: "Invitation sent, no answer yet",
    reviewNotInvited: "No rating invitation was created for this booking.",
    reviewNoComment: "No note left",
    statuses: {
      pending: "Pending",
      confirmed: "Confirmed",
      checked_in: "Waiting for technician",
      in_progress: "In progress",
      completed: "Completed",
      cancelled: "Cancelled",
      no_show: "No-show",
    },
    sources: { web: "Website", walk_in: "Walk-in", phone: "Phone" },
  },

  myDay: {
    title: "My day",
    subtitle: "Your bookings today",
    empty: "Nothing booked for you today.",
    ticket: "Ticket",
    station: "Station",
    customer: "Customer",
    notes: "Notes",
    design: "Design",
    confirmTicket: "Confirm the ticket number with her before you start.",
    start: "Start",
    finish: "Finish",
    waitingForDesk: "Waiting for the front desk to close it",
    elapsed: "Elapsed",
    expected: "Expected",
    done: "Done",
    totalWorked: "Total time worked",
    failed: "That didn't go through — refresh and try again.",
  },

  frontDesk: {
    title: "Front desk",
    subtitle: "Check a customer in by her ticket number",
    ticketLabel: "Ticket or booking number",
    ticketPlaceholder: "A12  or  RON-4F2K",
    search: "Find",
    checkIn: "Check in",
    close: "Close ticket",
    technician: "Technician",
    autoAssigned: "Assigned automatically",
    noneFree: "Nobody free — pick someone by hand",
    changeTech: "Change technician",
    readyToClose: "Ready to close",
    today: "Today",
    statCompleted: "Finished today",
    statInService: "In service now",
    statUpcoming: "Still to come today",
    statWaiting: "Waiting to check in",
    notFound: "No booking with that number today at this branch.",
    notToday: "That ticket isn't for today.",
    alreadyIn: "She's already checked in.",
    notCheckable: "This booking can't be checked in.",
    tooEarly: "She's early — check-in opens at",
    failed: "That didn't go through — try again.",
  },

  performance: {
    title: "Performance",
    subtitle: "How long each technician takes — commission is calculated later",
    technician: "Technician",
    services: "Services finished",
    avgService: "Average service time",
    avgExpected: "Against expected",
    avgWait: "Average wait",
    noData: "No finished services in this period.",
    period7: "7 days",
    period30: "30 days",
    periodToday: "Today",
    minutes: "min",
    faster: "faster",
    slower: "slower",
    commissionNote:
      "No money shown: the commission rule hasn't been set yet. These are the numbers it will be based on.",
  },

  availability: {
    title: "Availability",
    subtitle: "Opening hours, chairs and closures — these determine what can be booked",
    hours: "Opening hours",
    stations: "Chairs",
    closures: "Closures",
    weekday: "Day",
    opens: "Opens",
    closes: "Closes",
    closed: "Closed",
    addStation: "Add chair",
    stationLabel: "Label",
    qrCodes: "Chair QR codes",
    addClosure: "Add closure",
    from: "From",
    to: "To",
    reason: "Reason",
    noClosures: "No closures",
    weekdays: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    saved: "Saved",
  },

  giftCards: {
    title: "Gift cards",
    subtitle: "Issued cards, plus the values and designs offered on the site",
    tabIssued: "Issued",
    tabSetup: "Setup",
    issue: "Issue card",
    code: "Code",
    initial: "Initial value",
    balance: "Balance",
    buyer: "Buyer",
    recipient: "Recipient",
    status: "Status",
    expires: "Expires",
    issuedAt: "Issued",
    empty: "No cards issued yet",
    values: "Available values",
    designs: "Card designs",
    addValue: "Add value",
    amount: "Amount",
    ledger: "Transactions",
    adjust: "Adjust balance",
    adjustAmount: "Amount (negative to deduct)",
    adjustReason: "Reason",
    noTxns: "No transactions",
    message: "Message",
    cancelCard: "Cancel card",
    insufficient: "Insufficient balance",
    statuses: { active: "Active", redeemed: "Redeemed", expired: "Expired", cancelled: "Cancelled" },
  },

  customers: {
    title: "Customers",
    subtitle: "Profiles, history and notes",
    search: "Search by name or mobile",
    name: "Name",
    phone: "Mobile",
    email: "Email",
    bookingsCount: "Bookings",
    lifetime: "Lifetime value",
    lastVisit: "Last visit",
    notes: "Internal notes",
    blocked: "Blocked",
    blockedHint: "Cannot book through the website",
    history: "Booking history",
    noHistory: "No bookings",
    noShows: "No-shows",
    empty: "No customers yet",
    never: "Never",
  },

  staff: {
    title: "Staff",
    subtitle: "Accounts and permissions",
    invite: "Add staff",
    edit: "Edit staff",
    name: "Name",
    email: "Email",
    phone: "Mobile",
    role: "Role",
    branch: "Branch",
    allBranches: "All branches",
    password: "Password",
    passwordHint: "At least 8 characters — leave blank to keep unchanged",
    passwordRequired: "A password is required for a new account",
    active: "Active",
    lastLogin: "Last sign-in",
    never: "Never signed in",
    empty: "No staff accounts",
    emailTaken: "That email is already in use",
    cannotEscalate: "You cannot grant a role higher than your own",
    lastCeo: "The last CEO account cannot be deactivated",
    self: "You",
    deleteConfirm: "Delete this account?",
  },

  media: {
    title: "Media library",
    subtitle: "Every image used across the site",
    upload: "Upload",
    choose: "Choose image",
    change: "Change",
    remove: "Remove image",
    empty: "No images yet",
    hint: "WebP, PNG or JPEG · 5 MB max",
    badType: "Unsupported file type",
    tooLarge: "File is larger than 5 MB",
    uploadFailed: "Upload failed, please try again",
    deleteConfirm: "Delete this image?",
    inUse: "In use",
    dimensions: "Dimensions",
    size: "Size",
    localDriver:
      "Using local storage — uploads are written into the project folder. Set the Supabase keys before deploying.",
  },

  catalog: {
    title: "Services & add-ons",
    subtitle: "Prices, durations and images shown on the booking page",
    tabServices: "Services",
    tabAddons: "Add-ons",
    tabRemovals: "Removal",
    newService: "New service",
    newAddon: "New add-on",
    newRemoval: "New removal type",
    editService: "Edit service",
    editAddon: "Edit add-on",
    editRemoval: "Edit removal type",
    nameAr: "Name (Arabic)",
    nameEn: "Name (English)",
    descAr: "Description (Arabic)",
    descEn: "Description (English)",
    price: "Price",
    duration: "Duration (minutes)",
    durationHint: "Used to work out available appointment slots",
    refillDays: "Refill window (days)",
    refillDaysHint: "0 = no refill. Nails 30, lashes 14. The button shows in the customer's bookings for this long.",
    image: "Image",
    active: "Active",
    activeHint: "Inactive items are hidden from the site",
    seasonal: "Seasonal",
    seasonalHint: "Opens the seasonal designs pop-up",
    order: "Order",
    copyFromAr: "Copy from Arabic",
    missingAr: "Arabic name is the same as English",
    saved: "Saved",
    deleteConfirm: "Delete this item?",
    delete: "Delete",
    inactive: "Inactive",
    empty: "Nothing here yet",
    minutes: "min",
    inUseCannotDelete: "Can't delete: this item is attached to past bookings. Deactivate it instead.",
  },

  reviews: {
    title: "Reviews",
    subtitle: "What customers said after their ticket was ended.",
    avgService: "Average service rating",
    avgTech: "Average technician rating",
    outOfFive: "out of 5",
    noTechYet: "Bookings aren't assigned to technicians yet",
    responseRate: "Response rate",
    ofInvited: (answered: number, invited: number) => `${answered} of ${invited} invited`,
    when: "Appointment",
    service: "Service",
    technician: "Technician",
    serviceScore: "Service",
    techScore: "Technician",
    comment: "Note",
    pending: "Not answered",
    skipped: "Skipped",
    empty: "No reviews yet",
    emptyBody: "The invitation is sent automatically when a ticket is ended.",
  },

  promoCodes: {
    title: "Discount codes",
    subtitle: "Occasion codes — National Day, Eid, and whatever runs next.",
    newCode: "New code",
    editCode: "Edit code",
    code: "Code",
    codeHint: "Letters and digits only, no spaces.",
    type: "Discount type",
    percent: "Percentage",
    fixed: "Fixed amount",
    percentValue: "Percentage %",
    percentHint: "1 to 100",
    fixedValue: "Amount (SAR)",
    discount: "Discount",
    minTotal: "Minimum bill",
    minTotalHint: "Zero means no minimum.",
    startsAt: "Starts",
    endsAt: "Ends",
    always: "No window",
    window: "Window",
    maxUses: "Maximum uses",
    maxUsesHint: "Leave empty for unlimited.",
    used: "Used",
    activeLabel: "Active",
    inactive: "Off",
    activate: "Activate",
    deactivate: "Turn off",
    sar: "SAR",
    empty: "No discount codes",
    emptyBody: "Create one and it appears in the customer's checkout.",
    errors: {
      duplicate: "That code already exists",
      "code-format": "Codes must be letters and digits only",
      "percent-range": "A percentage can't be over 100",
      "bad-window": "The end date must be after the start date",
      "not-found": "That code no longer exists",
      invalid: "Check the fields",
      failed: "Something went wrong, please try again",
    },
  },

  common: {
    loading: "Loading…",
    save: "Save",
    cancel: "Cancel",
    soon: "Soon",
    comingSoon: "This section is under construction",
    none: "None",
    riyal: "SAR",
    add: "Add",
    edit: "Edit",
    saving: "Saving…",
    error: "Something went wrong, please try again",
    moveUp: "Move up",
    moveDown: "Move down",
  },
};

export const adminStrings = { ar, en } as const;
export type AdminLang = keyof typeof adminStrings;
